#include <LegacyCoreKit/FBSDKAccessToken.h>
#include <LegacyCoreKit/FBSDKAppEvents.h>
#include <LegacyCoreKit/FBSDKAppLink.h>
#include <LegacyCoreKit/FBSDKAppLinkNavigation.h>
#include <LegacyCoreKit/FBSDKAppLinkResolver.h>
#include <LegacyCoreKit/FBSDKAppLinkResolverRequestBuilder.h>
#include <LegacyCoreKit/FBSDKAppLinkResolving.h>
#include <LegacyCoreKit/FBSDKAppLinkReturnToRefererController.h>
#include <LegacyCoreKit/FBSDKAppLinkReturnToRefererView.h>
#include <LegacyCoreKit/FBSDKAppLinkTarget.h>
#include <LegacyCoreKit/FBSDKAppLinkUtility.h>
#include <LegacyCoreKit/FBSDKApplicationDelegate.h>
#include <LegacyCoreKit/FBSDKAuthenticationToken.h>
#include <LegacyCoreKit/FBSDKAuthenticationTokenClaims.h>
#include <LegacyCoreKit/FBSDKButton.h>
#include <LegacyCoreKit/FBSDKConstants.h>
#include <LegacyCoreKit/FBSDKCopying.h>
#include <LegacyCoreKit/FBSDKCoreKit.h>
#include <LegacyCoreKit/FBSDKDeviceButton.h>
#include <LegacyCoreKit/FBSDKDeviceViewControllerBase.h>
#include <LegacyCoreKit/FBSDKGraphErrorRecoveryProcessor.h>
#include <LegacyCoreKit/FBSDKGraphRequest.h>
#include <LegacyCoreKit/FBSDKGraphRequestConnecting.h>
#include <LegacyCoreKit/FBSDKGraphRequestConnection+GraphRequestConnecting.h>
#include <LegacyCoreKit/FBSDKGraphRequestConnection.h>
#include <LegacyCoreKit/FBSDKGraphRequestDataAttachment.h>
#include <LegacyCoreKit/FBSDKGraphRequestHTTPMethod.h>
#include <LegacyCoreKit/FBSDKGraphRequestProtocol.h>
#include <LegacyCoreKit/FBSDKLoggingBehavior.h>
#include <LegacyCoreKit/FBSDKMeasurementEvent.h>
#include <LegacyCoreKit/FBSDKMutableCopying.h>
#include <LegacyCoreKit/FBSDKProfile.h>
#include <LegacyCoreKit/FBSDKProfilePictureView.h>
#include <LegacyCoreKit/FBSDKSettings.h>
#include <LegacyCoreKit/FBSDKTestUsersManager.h>
#include <LegacyCoreKit/FBSDKURL.h>
#include <LegacyCoreKit/FBSDKUserAgeRange.h>
#include <LegacyCoreKit/FBSDKUtility.h>
#include <LegacyCoreKit/FBSDKWebViewAppLinkResolver.h>